# Generated by Django 5.2 on 2026-05-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
